include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - directives_ordering
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - library_private_types_in_public_api
    - only_throw_errors
    - no_leading_underscores_for_library_prefixes
    - prefer_relative_imports
    - prefer_single_quotes
    
analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"